services:
  api:
    build: .
    ports:
      - "8001:8000"
    restart: always
  app:
    # Image to use
    image: python:3.12
    # Working directory inside the container
    working_dir: /app
    ports:
      # Map port inside container to port 8000 on host
      - "8000:8000"
    volumes:
      # Allows for syncing files for updating during development
      - .:/app